environment: development
chdir: /www/documentcloud/sotw-docucloud 
address: 127.0.0.1
user: ec2-user
group: ec2-user
port: 4567
#pid: /path/to/app/current/myapp/tmp/thin.pid
rackup: /www/documentcloud/sotw-docucloud/config.ru
#log: /path/to/app/current/myapp/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
